name: Test, Build, Deploy Android

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
  
jobs:

 test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        with:
          # The Flutter version to make available on the path
          flutter-version: 1.24.0-10.2.pre
           # The Flutter build release channel
          channel: dev
      - run: flutter pub get
      - run: flutter  analyze
      - run: flutter test --coverage
